# Generated by Django 4.2.4 on 2023-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
